README.md
That theme is already mentioned a few lines earlier.
=> Remove duplicate from README

README.md
I made a dracula theme for listed, wanted to add it and a themes catagory for listed
=> Added Listed themes and a theme

README.md
=> Add Marcokai listed theme

README.md
=> add guide for installing Standard Notes on Linux

README.md
It currently doesn't have a specific title, so I added one that describes what it does. Feel free to make modifications.
=> add new clipping extension

README.md
https://github.com/matze/iridium
Feel free to reposition/translate this up/down in the list
Discovery credit: https://github.com/standardnotes/forum/issues/1135
=> add Iridum as the first 3rd party client with a GUI

README.md
Originally discovered via a post made on Reddit by the author: https://www.reddit.com/r/StandardNotes/comments/kljvyd/simple_less_distraction_theme_a_la_ia_writer/
=> add "Less Distraction Theme" by Alec Stein

README.md
Source: https://standardnotes.slack.com/archives/C53S4JER5/p1611793827004300
=> add the Yaru theme by Ari

README.md
=> add Callisto Theme

README.md
=> add Horizon Dark Theme

README.md
=> add gruvbox muted themes

README.md
Adding 5 new editors I created
=> Adding 5 new editors

README.md
I modified the Code Editor to include the folding functionality that's already included in CodeMirror. Since I thought this feature should have already been included, and was easy enough for me to implement, I thought I'd do it myself. This is a desired feature apparently in the community so I thought I'd share it.
=> Add folding code editor.

README.md
Added Components section under extensions and added the Pomodoro Timer Bar I wrote.
=> Added Components section and Pomodoro timer 

README.md
Added `JetBrains Mono` to the fonts list. This will give a more beautiful interface to the fonts, including the font ligature option.
This font needs to activate from the themes section. Theme called **JetBrains Mono**
=> Added JetBrains Mono to the fonts section

README.md
=> Move Standard Notes Writer from editors to themes

README.md
Added Kanban Editor to Awesome Standard Notes.
=> Added Kanban Editor

README.md
Added a link to the https://github.com/antonheitz/sn-tldraw-editor extension and hope it will help some people.
=> added free draw editor link

README.md
Hey, I added a Link to my quick guide for deploying and hosting the SN Server on ARM devices! :)
=> added ARM Server Guide link

README.md
Sorry for the inconvenience, I got  request to rename the editor.
=> rename editor & repository

README.md
Added guides I wrote on installing and creating extensions. Added Excalidraw, Quill, and Cosmos editor extensions.
Let me know if there are any issues.
=> Adding guides and editor extensions.

README.md
Updated description to reflect newer version featurs.
=> Updated BB10 Remmber tool description

README.md
=> Add Tui Markdown Editor

README.md
For some reason @nienow removed (https://github.com/jonhadfield/awesome-standard-notes/pull/68) my theme which was working and still is in desktop/web/android
=> Add markdown monospace

README.md
- Adds Serendipity theme
- Updates links for Horizon themes
=> Add Serendipity theme

README.md
I created a dark theme that is easy on the eyes.
=> add Dark Sense Theme

README.md
Created a moss theme - dark green theme with lower contrast text, orange accents.
=> Moss theme created and added to list
